# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += EasyVulkanFramework/EasyVulkanFramework.pro \
    EasyVulkanPythonScheduler/EasyVulkanPythonScheduler.pro \
    ChineseCharDemo/ChineseCharDemo.pro \
    EasyVulkanEditor/EasyVulkanEditor.pro \
    ConsoleWindow/ConsoleWindow.pro \
    /../../BaiduYunDownload/cwj066_11957348/test38/test38.pro \
    FileExplorerDemo/FileExplorerDemo.pro \
    PyModule/PyModule.pro \
    /EasyVulkanPropertyEditor/EasyVulkanPropertyEditor/EasyVulkanPropertyEditor.pro \
    ObjectTreeWidget/ObjectTreeWidget.pro
